version: "3.7"

services:

  pong:
    image: tantaelorg/test:interview-latest
    hostname: pong
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INITIALIZER=0
      - PYTHONUNBUFFERED=1
      - PUB_SERVER=tcp://*:5555
      - SUB_CLIENT=tcp://ping:5555
      - MAX_VALUE=10

  ping:
    image: tantaelorg/test:interview-latest
    hostname: ping
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pong
    environment:
      - INITIALIZER=1
      - PYTHONUNBUFFERED=1
      - PUB_SERVER=tcp://*:5555
      - SUB_CLIENT=tcp://pong:5555
      - MAX_VALUE=10
